spring:
  mvc:
    favicon:
      enabled: false
  output:
    ansi:
      enabled: always
  application:
    name: mall-iot-chuanyunapi
  profiles:
    active: test

app:
  name: mall-iot-chuanyunapi
  appkey: com.sankuai.mall.iot.chuanyunapi

server:
  tomcat:
    accesslog:
      directory: logs
      enabled: true
      prefix: localhost_access_log
      suffix: .log
      pattern: "%A|%h|%m|%t|%D|&quot;%r&quot;|&quot;%{Referer}i&quot;|&quot;%{User-Agent}i&quot;|%s|%S|%b|%{X-Request-ID}i|%{begin:msec}t|%{end:msec}t"
      rename-on-rotate: true
  port: 8082